# site settings
title: ahoxus
email: help@ahoxus.org
description: chaos up! # goes in the document head meta (for
#  search engines results) and in the feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://ahoxus.org # the base hostname & protocol for your site
enforce_ssl: "ahoxus.org"
github_url: https://github.com/ahoxus/ahoxus.github.io
twitter_username: ahoxus
github_username: ahoxus
include: [".well-known"]

# remember that tracking is a waste of resources. profit from sharing and caring instead #lifeprofit cregox.net/tracking 

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"
# jekyll configuration (usually?)
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true

image_path: /gallery/