# Site settings
title: ahoxus
email: help@ahoxus.org
description: chaos up! # goes in the document head meta (for
#  Google search results) and in the feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://ahoxus.org # the base hostname & protocol for your site
enforce_ssl: "ahoxus.org"
github_url: https://github.com/ahoxus/ahoxus.github.io
twitter_username: ahoxus
github_username: ahoxus
google_analytics: UA-4687862-18 # placed on head include
include: [".well-known"]

defaults:
  -
    scope:
      path: "talk"
      type: pages
    values:
      layout: talk # overrides previous default layout
      google_analytics: # placed on files by httrack and talk layout


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
